name = "xero-invoice-proxy"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "TOKENS"
id = "fcaf6ceff05343c9b2b3a167b49917d9"

[vars]
ALLOWED_ORIGIN = "https://edweiss412.github.io"
XERO_REDIRECT_URI = "https://xero-invoice-proxy.edweiss412.workers.dev/callback"
FRONTEND_URL = "https://edweiss412.github.io/freelance-tools/filename_generator.html"
GOOGLE_REDIRECT_URI = "https://xero-invoice-proxy.edweiss412.workers.dev/gmail/callback"

[triggers]
crons = ["*/5 * * * *"]
